const postsDemoData = [
  {
    company: "ASAC",
    position: "Senior developer",
    paid: "Paid Internship",
    type: "Part Time",
    experience: "Two Years",
    education: "Bachelors",
    industry: "Banking",
    salary: 150,
    city: "Amman",
    location: "Mecca Street",
    vacancies: 5,
    description: "Full Time senior developer with two year experience",
    supervisor_Name: "Raghad",
    subervisor_position: "Team Lead Tech",
    supervisor_phone_number: "077",
    endDate: "2022-6-05",
  },
  {
    company: "CC",
    position: "Senior developer",
    paid: "Paid Internship",
    type: "Full Time",
    experience: "Two Years",
    education: "Masters",
    industry: "Medical",
    salary: 150,
    city: "Amman",
    location: "Mecca Street",
    vacancies: 5,
    description: "Full Time senior developer with two year experience",
    supervisor_Name: "Jood",
    subervisor_position: "Team Lead Tech",
    supervisor_phone_number: "077",
    endDate: "2022-6-05",
  },
  {
    company: "Amazon",
    position: "Senior developer",
    paid: "Paid Internship",
    type: "Full Time",
    experience: "Two Years",
    education: "Phd",
    industry: "Education",
    salary: 150,
    city: "Amman",
    location: "Mecca Street",
    vacancies: 5,
    description: "Full Time senior developer with two year experience",
    supervisor_Name: "Gheed",
    subervisor_position: "Team Lead Tech",
    supervisor_phone_number: "077",
    endDate: "2022-6-05",
  },
  {
    company: "Facebook",
    position: "Senior developer",
    paid: "Paid Internship",
    type: "Full Time",
    experience: "Two Years",
    education: "Phd",
    industry: "Education",
    salary: 150,
    city: "Amman",
    location: "Mecca Street",
    vacancies: 5,
    description: "Full Time senior developer with two year experience",
    supervisor_Name: "Gheed",
    subervisor_position: "Team Lead Tech",
    supervisor_phone_number: "077",
    endDate: "2022-6-05",
  },
];

export default postsDemoData;
