const applicationData = [
{
  student: "Raghad",
  internship: "ASAC",
  type: "Full Time",
  homeFullAddress: "Mecca Street",
  location: "Remote",
  expected_salary: 150,
  coverletter: "Full Stack developer looking forward to improve my coding",
  resume: "raghad_resume.pdf",
},
{
  student: "Emad",
  internship: "Amazon",
  type: "Full Time",
  homeFullAddress: "Dhyet Alrasheed",
  location: "Remote",
  expected_salary: 150,
  coverletter: "Full Stack developer looking forward to improve my coding",
  resume: "raghad_resume.pdf",
},
{
  student: "Suhaib",
  internship: "ASAC",
  type: "Part Time",
  homeFullAddress: "Khalda",
  location: "Remote",
  expected_salary: 50,
  coverletter: "Full Stack developer looking forward to improve my coding",
  resume: "raghad_resume.pdf",
},
{
  student: "Ghaidaa",
  internship: "Google",
  type: "Part Time",
  homeFullAddress: "Seventh Circle",
  location: "OnSite",
  expected_salary: 150,
  coverletter: "Full Stack developer looking forward to improve my coding",
  resume: "raghad_resume.pdf",
},
{
  student: "Moayad",
  internship: "Amazon",
  type: "Part Time",
  homeFullAddress: "First Circle",
  location: "OnSite",
  expected_salary: 150,
  coverletter: "Full Stack developer looking forward to improve my coding",
  resume: "raghad_resume.pdf",
},
];

export default applicationData
