const poposalsDemoData = [
  {
    title: "Report 1",
    student: "Raghad",
    company: "Ghaida' Company",
    internship_application: "Ghaida' Company",
    remarks: "This is bar report, please resubmit",
    accepted: false,
  },
  {
    title: "Report 1",
    student: "Emad",
    company: "Ghaida' Company",
    internship_application: "Ghaida' Company",
    remarks: "This is bar report, please resubmit",
    accepted: true,
  },
  {
    title: "Report 2",
    student: "Suhaib",
    company: "Ghaida' Company",
    internship_application: "Ghaida' Company",
    remarks: "This is bar report, please resubmit",
    accepted: true,
  },
  {
    title: "Report 2",
    student: "Emad",
    company: "Ghaida' Company",
    internship_application: "Ghaida' Company",
    remarks: "This is bar report, please resubmit",
    accepted: false,
  },
  {
    title: "Report 3",
    student: "Raghad",
    company: "Ghaida' Company",
    internship_application: "Ghaida' Company",
    remarks: "This is bar report, please resubmit",
    accepted: true,
  },
  {
    title: "Report 4",
    student: "Suhaib",
    company: "Ghaida' Company",
    internship_application: "Ghaida' Company",
    remarks: "This is bar report, please resubmit",
    accepted: true,
  },
  {
    title: "Report 5",
    student: "Raghad",
    company: "Ghaida' Company",
    internship_application: "Ghaida' Company",
    remarks: "This is bar report, please resubmit",
    accepted: true,
  },
  {
    title: "Report 3",
    student: "Ghiadaa",
    company: "Ghaida' Company",
    internship_application: "Ghaida' Company",
    remarks: "This is bar report, please resubmit",
    accepted: true,
  },
  {
    title: "Report 4",
    student: "Ghiadaa",
    company: "Ghaida' Company",
    internship_application: "Ghaida' Company",
    remarks: "This is bar report, please resubmit",
    accepted: false,
  },
  {
    title: "Report 5",
    student: "Moayad",
    company: "Ghaida' Company",
    internship_application: "Ghaida' Company",
    remarks: "This is bar report, please resubmit",
    accepted: true,
  },
  {
    title: "Report 1",
    student: "Raghad",
    company: "Ghaida' Company",
    internship_application: "Ghaida' Company",
    remarks: "This is bar report, please resubmit",
    accepted: false,
  },
  {
    title: "Report 1",
    student: "Emad",
    company: "Ghaida' Company",
    internship_application: "Ghaida' Company",
    remarks: "This is bar report, please resubmit",
    accepted: true,
  },
];

export default poposalsDemoData
